### ISSUE TITLE
Validate assets in CI.

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/web#131]
Assets from `server/asset/asset.go` are no being validated in CI.

The `make validate-commit` rule lacks `assets` prerequisite because [it was removed](https://github.com/bblfsh/dashboard/pull/130/commits/397e5f6a21d44b7b3b09e121a9e70bdce452ce78) to fix a problem with the cache.
The problem was caused by [`moddate=1` hack](https://github.com/bblfsh/dashboard/pull/105/commits/f0f86d454cabc02545c0e7e482d34588cd322a20#diff-b67911656ef5d18c4ae36cb6741b7965R54), that caused the api to serve assets without a valid `Last-Modified` header, so they were always served from browser cache.

One possible solution could be to have two `assets` rules (with and without `modtime` hack);
- when commiting/pushing/testing assets, it would be used the `moddate=1` hack,
- when releasing, Travis would use the normal `make assets` rule to generate the proper assets and add them into the GH release and docker image

**Comment by carlosms** [comment]
What's the status of this after #192?

**Comment by smacker** [comment]
no assets - no need for validation 🎉
