### ISSUE TITLE
Adding .gif on documentation for Dashboard 

### ISSUE THREAD

**Issue by tsolakoua** [bblfsh/web#147]
While running Babelfish Dashboard through the instructions at the [documentation](https://doc.bblf.sh/using-babelfish/getting-started.html) I thought it would be nice to have a .gif showing the process and how you can locate parts of code in the UAST (that is with the yellow colors). 

I thought the issue should be in the documentation repo, as any changes would be reflected there, but it seems I am directed here :smiley: It might not be necessary change, it's just an idea.

**Comment by tsolakoua** [comment]
The instructions would be reflected in doc.bblfsh.sh, but I don't know if it could be added in README.md of the dashboard or any relevant documents. What do you think @bzz ?

**Comment by eiso** [comment]
Adding it to the README here makes sense to me.

**Comment by bzz** [comment]
@tsolakoua please, definitely feel free to submit a PR with small gif to this repository README.

Not sure about other places like https://doc.bblf.sh/ and https://docs.sourced.tech/babelfish/using-babelfish
