### ISSUE TITLE
Default port change from 80 to 8080

### ISSUE THREAD

**Issue by eiso** [bblfsh/web#148]
Currently the default port on the containerized babelfish dashboard is `80`. On our gitbase playground it is `8080`. I would like to change the default to `8181` or something similar so that we can have users run our stack using docker with `--network host` and not having conflicting ports. 

p.s. I am aware that with the `addr` flag we can choose a port, but I would like to make our defaults as simple as possible

**Comment by smola** [comment]
@eiso Why are you running with `--network host`? You should probably run with `-p 8181:80` instead.

**Comment by eiso** [comment]
@smola because `--link` is legacy and I needed to connect link the containers. Is there a better way?

**Comment by smola** [comment]
@eiso I didn't know link was deprecated! It seems using user defined networks would be the thing:

```
docker network create my-network
docker run --network my-network ...
```

**Comment by bzz** [comment]
Indeed, using `--net host` is also not very cross-platform, so custom network is the thing that docker-compose is doing as well.

Do you guys still think we should change the default or can the issue be resolved? 

Changing would most probably require PR to this repo and at least https://github.com/src-d/charts/blob/master/bblfsh-dashboard/values.yaml#L13

**Comment by smola** [comment]
Maybe it is more convenient for all web interfaces like this to run on the same port inside the container, so it is then easier to know which port to expose or connect to. Either 80 or 8080? The advantage of using 8080 is that we can run as non-root user inside the container if we ever decide to do that.

**Comment by bzz** [comment]
Let's change default, here and in chart to 8080
