### ISSUE TITLE
Missing bbflsh-web version in UI

### ISSUE THREAD

**Issue by carlosms** [bblfsh/web#159]
With the latest docker image v0.7.0:

![image](https://user-images.githubusercontent.com/1469173/46660687-e074ba00-cbb7-11e8-9271-fe370eeb41ea.png)

**Comment by smacker** [comment]
Fixed in 0.8.0:
<img width="300" alt="screen shot 2018-10-26 at 15 36 27" src="https://user-images.githubusercontent.com/406916/47569823-f9f65f80-d934-11e8-9d55-6af081a42e34.png">
