### ISSUE TITLE
Display parsing error with new go-client

### ISSUE THREAD

**Issue by smacker** [bblfsh/web#162]
we lost the ability to report that a driver can't parse source code.

Here is an issue and comment about it in client-go: bblfsh/client-go#82 (comment)

According to LA team, it's impossible right now to tell was it driver error or not.
As soon as the library adds a way to recognize parsing errors we must adapt it here.

**Comment by dennwc** [comment]
Fixed in bblfsh. Make sure you have the latest `client-go.v3` installed, `bblfshd` 2.9.x and `go-driver` 2.3.x (more drivers to come). Check https://github.com/bblfsh/sdk/pull/321 for details on supported error codes.
