### ISSUE TITLE
Use the same way to handle go-bindata as other projects

### ISSUE THREAD

**Issue by smacker** [bblfsh/web#192]
Looks like now we have to commit `asset.go`, but it could be avoided as done in other projects.

**Comment by dpordomingo** [comment]
I think it's the opposite; we're [not pushing `assets.go` file in new projects](https://github.com/src-d/lookout/blob/master/.gitignore#L19).
But [we starting using `esc`](https://github.com/src-d/lookout/pull/438).

**Comment by smacker** [comment]
I mean we have to push `asset.go` right now for bblfsh/web. And I propose to change it.
esc or bindata isn't very important.

**Comment by dpordomingo** [comment]
updated the issue description to reflect that. Thanks!

**Comment by smacker** [comment]
Sorry, this issue wasn't in TODO but it annoys me A LOT every time I do anything in this project. And I spend more time figuring out why my changes don't work, then figuring how to re-create assets, push and so on than just freaking fixing it once and for all.
