### ISSUE TITLE
@type XPath does not work in Semantic mode

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/web#196]
I search by `//*[@type='uast:FunctionGroup']` XPath in Semantic mode and get 0 results. Tried Go and Python samples. This is unexpected, because, e.g. `//*[@role='Comment']` works.

Having played a little, I see that no `@type`-based XPath works for all the samples.

P.S.
`//name` in Java and `//Name` in Go work, too.

**Comment by dennwc** [comment]
`@type` maps directly to XML node name/type, so should be: `//uast:FunctionGroup`.

**Comment by vmarkovtsev** [comment]
This indeed works.

**Comment by vmarkovtsev** [comment]
Right, RTFM: it is written in the docs.
